### PR TITLE
graph aligner pipeline

### PR DESCRIPTION
**Pull request by jorgeavilacartes**
Graph Aligner
- ONT and Illumina rules
- yaml environment
- incorporated in Snakefile

### CODE REVIEW

**Review by sciccolella — CHANGES_REQUESTED** [review]
please use threads and params as used in othe rules

**Comment by sciccolella** [comment]
also the output should be a GAF

**Comment by jorgeavilacartes** [comment]
both changes were updated
commit [4cba835](https://github.com/PangaiaProject/alpang_hackathon/pull/5/commits/4cba835689cc195fb6fed232822aaa7294ccf43c)

**Review by sciccolella — CHANGES_REQUESTED** [review]
Excellent, now please remove the comments added to `align/workflow/Snakefile` :)

**Pull request merged**
